--- # Install PHP7

- name: Check if PHP is installed.
  command: which /usr/local/bin/php
  changed_when: false
  failed_when: false
  register: php_installed

- name: Check if composer installed
  command: which /usr/bin/composer
  changed_when: false
  failed_when: false
  register: composer_installed

- name: Add export path bashrc for /usr/local/bin 
  shell: echo 'export PATH=$PATH:/usr/local/bin'>>/root/.bashrc

- name: Add repo
  shell: yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y
  when: php_installed.rc != 0

- name: Enable remi php 71
  shell: yum-config-manager --enable remi-php71
  when: php_installed.rc != 0

- name: Install php 7.1 & packages 
  yum:
    name: '{{ php.packages }}'
    state: latest

- name: Download composer installer
  shell: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  when: composer_installed.rc != 0

- name: Install composer under /usr/bin/
  shell: php composer-setup.php --install-dir=/usr/bin --filename=composer
  when: composer_installed.rc != 0

- name: Remove composer installer
  shell: php -r "unlink('composer-setup.php');"
  when: composer_installed.rc != 0

- name: Create php custom.ini file
  template: >
    src="php-custom-config.j2"
    dest="/etc/php.d/custom.ini"
  when: php_installed.rc != 0

- name: Php-Fpm listen owner user
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.owner = nobody' line='listen.owner = vagrant'"

- name: Php-Fpm listen group
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?listen.group = nobody' line='listen.group = vagrant'"

- name: Php-Fpm user
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?user = nobody' line='user = vagrant'"

- name: Php-Fpm group user
  lineinfile: "dest=/etc/php-fpm.d/www.conf state=present regexp='^;?group = nobody' line='group = vagrant'"

- name: Enable php-fpm service
  shell: systemctl enable php-fpm.service

- name: Reload systemctl
  shell: systemctl daemon-reload

- name: Install pear modules
  shell: PHP_PEAR_PHP_BIN=/usr/bin/php /usr/bin/pecl install {{ php.peclpackages }}
      
- service:
    name: php-fpm
    state: restarted

