--- # Ansible playbook for centos 7 & php7 environment

#- hosts: '{{ server.hostname }}'
- hosts: 'all'
#  remote_user: '{{ server.remote_user }}'
  become: yes
  become_method: sudo
  connection: ssh
  vars_files:
    - vars.yml

  roles:
    - general
    - php
    - nginx
  
