--- # General variable list for installation
server:
    hostname: vagrant-centos7
    remote_user: vagrant
    epel: epel-release
    packages: [vim-common, vim, git, htop, curl, wget, tmux, zsh, openssl, libzip, libzip-devel, autoconf, bison, re2c, glibc-devel, libxml2-devel, libmcrypt-devel, libcurl-devel, bzip2-devel, libjpeg-devel, libpng-devel, openssl-devel, postgresql-devel, aspell-devel, readline-devel, librabbitmq, librabbitmq-devel, yum-utils, mlocate]
    timezone: Europe/Istanbul
    locale: en_US.UTF-8
nginx:
    url: http://nginx.org/download/nginx-1.12.0.tar.gz
    version: nginx-1.12.0
    download_path: /usr/local/src
    configure_string: --prefix=/usr/local/nginx --user=vagrant --group=vagrant --without-http_autoindex_module --without-http_ssi_module --with-http_ssl_module --with-http_stub_status_module --with-http_realip_module
    docroot: /var/www/local.dev
    servername: local.dev
postgres:
    root_password: '123456'
    database: db
    user: vagrant
    password: '123456'
    dump: ''
redis:
    port: '6379'
rabbitmq:
    user: test
    password: '123456'
    plugins: [rabbitmq_management]
php:
    url: http://ro1.php.net/get/php-7.1.12.tar.gz/from/this/mirror
    version: php-7.1.12
    download_path: /usr/local/src
    packages: [php, php-common, php-intl, php-mcrypt, php-soap, php-pdo, php-pgsql, php-opcache, php-mongodb, php-bcmath, php-gd, php-zip, php-pear]
    configure_string: "--with-config-file-path=/etc/php --with-config-file-scan-dir=/etc/php/conf.d --enable-bcmath --enable-exif --enable-dba --enable-opcache --enable-ftp --with-gettext --with-gd --enable-mbstring --with-bz2 --with-mhash --enable-mysqlnd --with-pdo-mysql=mysqlnd --with-openssl --enable-pcntl --with-pspell --enable-shmop --enable-soap --enable-sockets --enable-sysvmsg --enable-sysvsem --enable-sysvshm --enable-wddx --enable-zip --with-readline --with-curl --with-pcre-regex --disable-cgi --enable-fpm --with-pgsql --with-pdo-pgsql"
    peclpackages: "amqp xdebug"

